package Jpetstore.autom;

import java.util.regex.Pattern;
import java.util.concurrent.TimeUnit;
import org.junit.*;
import static org.junit.Assert.*;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.Select;

public class NouveauTest {
	private WebDriver driver;
	private boolean acceptNextAlert = true;
	private StringBuffer verificationErrors = new StringBuffer();

	@Before
	public void setUp() throws Exception {
		System.setProperty("webdriver.gecko.driver", "C:\\Users\\formation\\Desktop\\SUT\\geckodriver.exe");
		driver = new FirefoxDriver();
		driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
	}
	
	
	@After
	public void tearDown() throws Exception {
		driver.quit();
		String verificationErrorString = verificationErrors.toString();
		if (!"".equals(verificationErrorString)) {
			fail(verificationErrorString);
		}
	}

	@Test
	public void testUntitledTestCase() throws Exception {
		driver.get("http://localhost:8181/jpetstore/");
		driver.findElement(By.linkText("Enter the Store")).click();
		// Connexion au logiciel
		driver.findElement(By.linkText("Sign In")).click();
		driver.findElement(By.name("username")).clear();
		driver.findElement(By.name("username")).sendKeys("ACID");
		driver.findElement(By.name("password")).clear();
		driver.findElement(By.name("password")).sendKeys("ACID");
		driver.findElement(By.name("signon")).click();
		driver.findElement(By.xpath("//div[@id='QuickLinks']/a/img")).click();
		driver.findElement(By.linkText("FI-SW-01")).click();
		driver.findElement(By.linkText("EST-1")).click();
		driver.findElement(By.linkText("Add to Cart")).click();
		driver.findElement(By.xpath("//div[@id='QuickLinks']/a/img")).click();
		driver.findElement(By.linkText("FI-SW-02")).click();
		driver.findElement(By.linkText("EST-3")).click();
		driver.findElement(By.linkText("Add to Cart")).click();
		driver.findElement(By.xpath("//div[@id='QuickLinks']/a/img")).click();
		driver.findElement(By.linkText("FI-FW-01")).click();
		driver.findElement(By.linkText("EST-4")).click();
		driver.findElement(By.linkText("Add to Cart")).click();
		driver.findElement(By.xpath("//div[@id='QuickLinks']/a/img")).click();
		driver.findElement(By.linkText("FI-SW-01")).click();
		driver.findElement(By.linkText("EST-2")).click();
		driver.findElement(By.linkText("Add to Cart")).click();
		driver.findElement(By.xpath("//div[@id='QuickLinks']/a/img")).click();
		driver.findElement(By.linkText("FI-SW-02")).click();
		driver.findElement(By.xpath("//div[@id='LogoContent']/a/img")).click();
		driver.findElement(By.xpath("//div[@id='QuickLinks']/a/img")).click();
		driver.findElement(By.linkText("FI-FW-01")).click();
		driver.findElement(By.linkText("EST-5")).click();
		driver.findElement(By.linkText("Add to Cart")).click();
		driver.findElement(By.xpath("//div[@id='QuickLinks']/a/img")).click();
		driver.findElement(By.linkText("FI-FW-02")).click();
		driver.findElement(By.linkText("EST-20")).click();
		driver.findElement(By.linkText("Add to Cart")).click();
		driver.findElement(By.xpath("//div[@id='LogoContent']/a/img")).click();
		driver.findElement(By.xpath("//div[@id='QuickLinks']/a/img")).click();
		driver.findElement(By.linkText("FI-FW-02")).click();
		driver.findElement(By.linkText("EST-21")).click();
		driver.findElement(By.linkText("Add to Cart")).click();
		driver.findElement(By.xpath("//div[@id='QuickLinks']/a[2]/img")).click();
		driver.findElement(By.linkText("K9-BD-01")).click();
		driver.findElement(By.linkText("EST-6")).click();
		driver.findElement(By.linkText("Add to Cart")).click();
		driver.findElement(By.xpath("//div[@id='QuickLinks']/a[2]/img")).click();
		driver.findElement(By.linkText("K9-BD-01")).click();
		driver.findElement(By.linkText("EST-7")).click();
		driver.findElement(By.linkText("Add to Cart")).click();
		driver.findElement(By.xpath("//div[@id='QuickLinks']/a[2]/img")).click();
		driver.findElement(By.linkText("K9-PO-02")).click();
		driver.findElement(By.xpath("//div[@id='Catalog']/table/tbody/tr[2]/td")).click();
		driver.findElement(By.linkText("Add to Cart")).click();
		driver.findElement(By.xpath("//div[@id='QuickLinks']/a[2]/img")).click();
		driver.findElement(By.linkText("K9-DL-01")).click();
		driver.findElement(By.linkText("EST-9")).click();
		driver.findElement(By.linkText("Add to Cart")).click();
		driver.findElement(By.xpath("//div[@id='QuickLinks']/a[2]/img")).click();
		driver.findElement(By.linkText("K9-DL-01")).click();
		driver.findElement(By.linkText("EST-10")).click();
		driver.findElement(By.linkText("Add to Cart")).click();
		driver.findElement(By.xpath("//div[@id='QuickLinks']/a[2]/img")).click();
		driver.findElement(By.linkText("K9-RT-01")).click();
		driver.findElement(By.linkText("EST-28")).click();
		driver.findElement(By.linkText("Add to Cart")).click();
		driver.findElement(By.xpath("//div[@id='QuickLinks']/a[2]/img")).click();
		driver.findElement(By.linkText("K9-RT-01")).click();
		driver.findElement(By.xpath("//div[@id='QuickLinks']/a[2]/img")).click();
		driver.findElement(By.linkText("K9-RT-02")).click();
		driver.findElement(By.linkText("EST-23")).click();
		driver.findElement(By.linkText("Add to Cart")).click();
		driver.findElement(By.xpath("//div[@id='QuickLinks']/a[2]/img")).click();
		driver.findElement(By.linkText("K9-RT-02")).click();
		driver.findElement(By.linkText("EST-22")).click();
		driver.findElement(By.id("Catalog")).click();
		driver.findElement(By.linkText("Add to Cart")).click();
		driver.findElement(By.xpath("//div[@id='QuickLinks']/a[2]/img")).click();
		driver.findElement(By.linkText("K9-RT-02")).click();
		driver.findElement(By.linkText("EST-24")).click();
		driver.findElement(By.linkText("Add to Cart")).click();
		driver.findElement(By.xpath("//div[@id='QuickLinks']/a[2]/img")).click();
		driver.findElement(By.linkText("K9-RT-02")).click();
		driver.findElement(By.linkText("EST-25")).click();
		driver.findElement(By.linkText("Add to Cart")).click();
		driver.findElement(By.xpath("//div[@id='QuickLinks']/a[2]/img")).click();
		driver.findElement(By.linkText("K9-CW-01")).click();
		driver.findElement(By.linkText("EST-26")).click();
		driver.findElement(By.linkText("Add to Cart")).click();
		driver.findElement(By.xpath("//div[@id='QuickLinks']/a[2]/img")).click();
		driver.findElement(By.linkText("K9-CW-01")).click();
		driver.findElement(By.linkText("EST-27")).click();
		driver.findElement(By.linkText("Add to Cart")).click();
		//driver.findElement(By.id("QuickLinks")).click();
		driver.findElement(By.xpath("//div[@id='QuickLinks']/a[3]/img")).click();
		driver.findElement(By.linkText("RP-SN-01")).click();
		driver.findElement(By.linkText("EST-11")).click();
		driver.findElement(By.linkText("Add to Cart")).click();
		driver.findElement(By.xpath("//div[@id='QuickLinks']/a[3]/img")).click();
		driver.findElement(By.linkText("RP-SN-01")).click();
		driver.findElement(By.linkText("EST-12")).click();
		driver.findElement(By.linkText("Add to Cart")).click();
		driver.findElement(By.xpath("//div[@id='QuickLinks']/a[3]/img")).click();
		driver.findElement(By.linkText("RP-LI-02")).click();
		driver.findElement(By.linkText("EST-13")).click();
		driver.findElement(By.linkText("Add to Cart")).click();
		driver.findElement(By.xpath("//div[@id='QuickLinks']/a[4]/img")).click();
		driver.findElement(By.linkText("FL-DSH-01")).click();
		driver.findElement(By.linkText("EST-14")).click();
		driver.findElement(By.linkText("Add to Cart")).click();
		driver.findElement(By.xpath("//div[@id='QuickLinks']/a[4]/img")).click();
		driver.findElement(By.linkText("FL-DSH-01")).click();
		driver.findElement(By.linkText("EST-15")).click();
		driver.findElement(By.linkText("Add to Cart")).click();
		driver.findElement(By.xpath("//div[@id='QuickLinks']/a[4]/img")).click();
		driver.findElement(By.linkText("FL-DLH-02")).click();
		driver.findElement(By.linkText("EST-16")).click();
		driver.findElement(By.linkText("Add to Cart")).click();
		driver.findElement(By.xpath("//div[@id='QuickLinks']/a[4]/img")).click();
		driver.findElement(By.linkText("FL-DLH-02")).click();
		driver.findElement(By.linkText("EST-17")).click();
		driver.findElement(By.linkText("Add to Cart")).click();
		driver.findElement(By.xpath("//div[@id='QuickLinks']/a[5]/img")).click();
		driver.findElement(By.linkText("AV-CB-01")).click();
		driver.findElement(By.linkText("EST-18")).click();
		driver.findElement(By.linkText("Add to Cart")).click();
		driver.findElement(By.xpath("//div[@id='QuickLinks']/a[5]/img")).click();
		driver.findElement(By.linkText("AV-SB-02")).click();
		driver.findElement(By.xpath("//div[@id='Catalog']/table/tbody/tr[2]/td")).click();
		//driver.findElement(By.linkText("EST-19")).click();
		driver.findElement(By.linkText("Add to Cart")).click();
		driver.findElement(By.name("EST-1")).click();
		driver.findElement(By.name("EST-1")).sendKeys(Keys.DOWN);
		driver.findElement(By.name("EST-1")).clear();
		driver.findElement(By.name("EST-1")).sendKeys("2");
		driver.findElement(By.name("EST-3")).click();
		driver.findElement(By.name("EST-3")).clear();
		driver.findElement(By.name("EST-3")).sendKeys("3");
		driver.findElement(By.name("EST-4")).click();
		driver.findElement(By.name("EST-4")).clear();
		driver.findElement(By.name("EST-4")).sendKeys("4");
		driver.findElement(By.name("EST-2")).click();
		driver.findElement(By.name("EST-2")).clear();
		driver.findElement(By.name("EST-2")).sendKeys("5");
		driver.findElement(By.name("EST-5")).click();
		driver.findElement(By.name("EST-5")).clear();
		driver.findElement(By.name("EST-5")).sendKeys("6");
		driver.findElement(By.name("EST-20")).click();
		driver.findElement(By.name("EST-20")).clear();
		driver.findElement(By.name("EST-20")).sendKeys("7");
		driver.findElement(By.name("EST-21")).click();
		driver.findElement(By.name("EST-21")).clear();
		driver.findElement(By.name("EST-21")).sendKeys("8");
		driver.findElement(By.name("EST-6")).click();
		driver.findElement(By.name("EST-6")).clear();
		driver.findElement(By.name("EST-6")).sendKeys("9");
		driver.findElement(By.name("EST-7")).click();
		driver.findElement(By.name("EST-7")).clear();
		driver.findElement(By.name("EST-7")).sendKeys("10");
		driver.findElement(By.name("EST-8")).click();
		driver.findElement(By.name("EST-8")).clear();
		driver.findElement(By.name("EST-8")).sendKeys("11");
		driver.findElement(By.name("EST-9")).click();
		driver.findElement(By.name("EST-9")).clear();
		driver.findElement(By.name("EST-9")).sendKeys("15");
		driver.findElement(By.name("EST-10")).click();
		driver.findElement(By.name("EST-10")).clear();
		driver.findElement(By.name("EST-10")).sendKeys("10");
		driver.findElement(By.name("EST-28")).click();
		driver.findElement(By.name("EST-28")).clear();
		driver.findElement(By.name("EST-28")).sendKeys("50");
		driver.findElement(By.name("EST-23")).click();
		driver.findElement(By.name("EST-23")).clear();
		driver.findElement(By.name("EST-23")).sendKeys("222");
		driver.findElement(By.name("EST-22")).click();
		driver.findElement(By.name("EST-22")).clear();
		driver.findElement(By.name("EST-22")).sendKeys("30");
		driver.findElement(By.name("EST-24")).click();
		driver.findElement(By.name("EST-24")).clear();
		driver.findElement(By.name("EST-24")).sendKeys("50");
		driver.findElement(By.name("EST-25")).click();
		driver.findElement(By.name("EST-25")).clear();
		driver.findElement(By.name("EST-25")).sendKeys("4");
		driver.findElement(By.name("EST-26")).click();
		driver.findElement(By.name("EST-26")).clear();
		driver.findElement(By.name("EST-26")).sendKeys("9");
		driver.findElement(By.name("EST-27")).click();
		driver.findElement(By.name("EST-27")).clear();
		driver.findElement(By.name("EST-27")).sendKeys("5");
		driver.findElement(By.name("EST-11")).click();
		driver.findElement(By.name("EST-11")).clear();
		driver.findElement(By.name("EST-11")).sendKeys("4");
		driver.findElement(By.name("EST-12")).click();
		driver.findElement(By.name("EST-12")).clear();
		driver.findElement(By.name("EST-12")).sendKeys("6");
		driver.findElement(By.name("EST-13")).click();
		driver.findElement(By.name("EST-13")).clear();
		driver.findElement(By.name("EST-13")).sendKeys("8");
		driver.findElement(By.name("EST-14")).click();
		driver.findElement(By.name("EST-14")).clear();
		driver.findElement(By.name("EST-14")).sendKeys("8000");
		driver.findElement(By.name("EST-15")).click();
		driver.findElement(By.name("EST-15")).clear();
		driver.findElement(By.name("EST-15")).sendKeys("500");
		driver.findElement(By.name("EST-16")).click();
		driver.findElement(By.name("EST-16")).clear();
		driver.findElement(By.name("EST-16")).sendKeys("500");
		driver.findElement(By.name("EST-17")).click();
		driver.findElement(By.name("EST-17")).clear();
		driver.findElement(By.name("EST-17")).sendKeys("100");
		driver.findElement(By.name("EST-18")).click();
		driver.findElement(By.name("EST-18")).clear();
		driver.findElement(By.name("EST-18")).sendKeys("300");
		driver.findElement(By.name("EST-19")).click();
		driver.findElement(By.name("EST-19")).clear();
		driver.findElement(By.name("EST-19")).sendKeys("626");
		driver.findElement(By.name("updateCartQuantities")).click();
		//driver.findElement(By.xpath("(//a[contains(text(),'Remove')])[8]")).click();
		//driver.findElement(By.xpath("(//a[contains(text(),'Remove')])[18]")).click();
		//driver.findElement(By.xpath("//html")).click();
		//driver.findElement(By.xpath("(//a[contains(text(),'Remove')])[10]")).click();
		driver.findElement(By.linkText("Proceed to Checkout")).click();
		/*
		 * driver.findElement(By.name("username")).clear();
		 * driver.findElement(By.name("username")).click();
		 * driver.findElement(By.name("username")).sendKeys("ACID");
		 * driver.findElement(By.name("password")).click();
		 * driver.findElement(By.name("password")).clear();
		 * driver.findElement(By.name("password")).sendKeys("ACID");
		 * driver.findElement(By.name("signon")).click();
		 * driver.findElement(By.xpath("//div[@id='QuickLinks']/a[4]/img")).click();
		 * driver.findElement(By.linkText("Sign Out")).click();
		 */
		driver.findElement(By.name("img_cart")).click();
		driver.findElement(By.xpath("//div[@id='QuickLinks']/a/img")).click();
		driver.findElement(By.linkText("FI-SW-02")).click();
		driver.findElement(By.linkText("EST-3")).click();
		driver.findElement(By.linkText("Add to Cart")).click();
		driver.findElement(By.name("EST-3")).click();
		driver.findElement(By.name("EST-3")).clear();
		driver.findElement(By.name("EST-3")).sendKeys("50");
		driver.findElement(By.name("updateCartQuantities")).click();
		driver.findElement(By.linkText("Proceed to Checkout")).click();
		driver.findElement(By.name("order.cardType")).click();
		new Select(driver.findElement(By.name("order.cardType"))).selectByVisibleText("MasterCard");
		driver.findElement(By.xpath("//option[@value='MasterCard']")).click();
		driver.findElement(By.name("order.creditCard")).sendKeys("1234567890123");
		driver.findElement(By.name("order.expiryDate")).click();
		driver.findElement(By.name("order.billToFirstName")).sendKeys("AHAHAHAHAHAHAHAHAHAHAH");
		driver.findElement(By.name("order.billToLastName")).sendKeys("YOLO");
		driver.findElement(By.name("order.billAddress1")).sendKeys("42 LULU DTA YOLO SWAG BISOUS");
		driver.findElement(By.name("order.billAddress2")).sendKeys("IBIRU IDK BOOM");
		driver.findElement(By.name("order.billCity")).sendKeys("EXPLOSION TORGUE AHA");
		driver.findElement(By.name("order.billState")).sendKeys("NOT A NAZI AGAIN");
		driver.findElement(By.name("order.billZip")).sendKeys("42000");
		driver.findElement(By.name("order.billCountry")).sendKeys("ATLANTIS");
		Thread.sleep(5000);
		driver.findElement(By.name("newOrder")).click();
		driver.findElement(By.linkText("Confirm")).click();
		driver.findElement(By.linkText("Return to Main Menu")).click();
	}


}
